# system configuration
system:
  env: develop
  addr: 9092
  use-captcha: true

# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: "backend"
  username: "postgres"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# zap configuration
zap:
  level: info
  format: console
  prefix: '[backend]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# jwt configuration
jwt:
  signing-key: "qmPlus"
  expires-time: 86400
  issuer: "backend"

# casbin configuration
casbin:
  model-path: "assets/rbac_model.conf"

pack:
  server: "http://192.168.1.26:8889"                 # 打包模块URL
  publish-path: "/Users/mac/Code/tutorials/publish"   # 打包后的文件存放路径（发布目录）

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# ipfs configuration
ipfs:
  - api: "http://ipfs.io/ipfs"
    upload-api: "http://192.168.1.10:3022/v1"

airdrop:
  verify-key: "123456"                   # 校验key
  api: "http://192.168.1.10:8105"        # 回调接口

# local configuration
local:
  path: 'uploads/file'

# quest configuration
quest:
  encrypt-key: "eb5a5bb2-ebbd-45cc-9d37-77a9377f2aca"

# translate configuration
translate:
  github-repo: "https://github.com/decert-me/document"
  github-branch: "main"