# system configuration
system:
  env: develop
  addr: 9092
  use-captcha: true

# pgsql configuration
pgsql:
  path: "127.0.0.1"
  port: "5432"
  config: ""
  db-name: "backend"
  username: "postgres"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# zap configuration
zap:
  level: info
  format: console
  prefix: '[backend]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# jwt configuration
jwt:
  signing-key: "qmPlus"
  expires-time: 86400
  issuer: "backend"

# casbin configuration
casbin:
  model-path: "assets/rbac_model.conf"

pack:
  path: "/home/cdeer/code/decert-go/admin/tutorials"         # tutorials 项目路径
  publish-path: "/home/cdeer/code/decertme/tutorials/build"  # 打包后的路径

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80